# Alarms for the three things that page: targets the ALB considers unhealthy,
# 5xx responses, and the database running out of CPU, storage or memory.
# Alarms always exist so they are visible in the console; they only notify
# when alarm_email or alarm_actions is set.

locals {
  name_prefix = "${var.project_name}-${var.environment}"
  actions     = concat(var.alarm_actions, aws_sns_topic.alarms[*].arn)
}

resource "aws_sns_topic" "alarms" {
  count = var.alarm_email != "" ? 1 : 0

  name = "${local.name_prefix}-alarms"

  tags = merge(var.tags, {
    Name = "${local.name_prefix}-alarms"
  })
}

# The subscription stays "pending confirmation" until the address clicks the
# link in the email AWS sends.
resource "aws_sns_topic_subscription" "alarm_email" {
  count = var.alarm_email != "" ? 1 : 0

  topic_arn = aws_sns_topic.alarms[0].arn
  protocol  = "email"
  endpoint  = var.alarm_email
}

# One alarm per target group. The inactive colour has no registered targets,
# so its metric is missing rather than zero; missing is treated as healthy.
resource "aws_cloudwatch_metric_alarm" "unhealthy_targets" {
  for_each = var.target_group_arn_suffixes

  alarm_name          = "${local.name_prefix}-${replace(each.key, "_", "-")}-unhealthy-targets"
  alarm_description   = "At least one target in the ${each.key} target group is failing ALB health checks"
  namespace           = "AWS/ApplicationELB"
  metric_name         = "UnHealthyHostCount"
  statistic           = "Maximum"
  period              = 60
  evaluation_periods  = 3
  threshold           = 0
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    LoadBalancer = var.alb_arn_suffix
    TargetGroup  = each.value
  }

  alarm_actions = local.actions
  ok_actions    = local.actions

  tags = var.tags
}

# 5xx generated by the ALB itself: no healthy targets, or targets timing out.
resource "aws_cloudwatch_metric_alarm" "alb_5xx" {
  alarm_name          = "${local.name_prefix}-alb-5xx"
  alarm_description   = "The load balancer returned more than ${var.alb_5xx_threshold} 5xx responses of its own in 5 minutes"
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HTTPCode_ELB_5XX_Count"
  statistic           = "Sum"
  period              = 300
  evaluation_periods  = 1
  threshold           = var.alb_5xx_threshold
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    LoadBalancer = var.alb_arn_suffix
  }

  alarm_actions = local.actions
  ok_actions    = local.actions

  tags = var.tags
}

# 5xx returned by the application containers.
resource "aws_cloudwatch_metric_alarm" "target_5xx" {
  alarm_name          = "${local.name_prefix}-target-5xx"
  alarm_description   = "Application targets returned more than ${var.target_5xx_threshold} 5xx responses in 5 minutes"
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HTTPCode_Target_5XX_Count"
  statistic           = "Sum"
  period              = 300
  evaluation_periods  = 1
  threshold           = var.target_5xx_threshold
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    LoadBalancer = var.alb_arn_suffix
  }

  alarm_actions = local.actions
  ok_actions    = local.actions

  tags = var.tags
}

resource "aws_cloudwatch_metric_alarm" "rds_cpu" {
  alarm_name          = "${local.name_prefix}-rds-cpu"
  alarm_description   = "Database CPU above ${var.rds_cpu_threshold}% for 15 minutes"
  namespace           = "AWS/RDS"
  metric_name         = "CPUUtilization"
  statistic           = "Average"
  period              = 300
  evaluation_periods  = 3
  threshold           = var.rds_cpu_threshold
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "missing"

  dimensions = {
    DBInstanceIdentifier = var.rds_identifier
  }

  alarm_actions = local.actions
  ok_actions    = local.actions

  tags = var.tags
}

# Storage autoscaling grows the volume, but only up to max_allocated_storage,
# and a full volume takes the database down.
resource "aws_cloudwatch_metric_alarm" "rds_free_storage" {
  alarm_name          = "${local.name_prefix}-rds-free-storage"
  alarm_description   = "Database free storage below ${var.rds_free_storage_threshold_bytes / 1073741824} GiB"
  namespace           = "AWS/RDS"
  metric_name         = "FreeStorageSpace"
  statistic           = "Average"
  period              = 300
  evaluation_periods  = 1
  threshold           = var.rds_free_storage_threshold_bytes
  comparison_operator = "LessThanThreshold"
  treat_missing_data  = "missing"

  dimensions = {
    DBInstanceIdentifier = var.rds_identifier
  }

  alarm_actions = local.actions
  ok_actions    = local.actions

  tags = var.tags
}

resource "aws_cloudwatch_metric_alarm" "rds_freeable_memory" {
  alarm_name          = "${local.name_prefix}-rds-freeable-memory"
  alarm_description   = "Database freeable memory below ${var.rds_freeable_memory_threshold_bytes / 1048576} MiB for 15 minutes"
  namespace           = "AWS/RDS"
  metric_name         = "FreeableMemory"
  statistic           = "Average"
  period              = 300
  evaluation_periods  = 3
  threshold           = var.rds_freeable_memory_threshold_bytes
  comparison_operator = "LessThanThreshold"
  treat_missing_data  = "missing"

  dimensions = {
    DBInstanceIdentifier = var.rds_identifier
  }

  alarm_actions = local.actions
  ok_actions    = local.actions

  tags = var.tags
}

# The backend is redeployed after every database password rotation. If that
# fails, running tasks keep a password that no longer works and the next
# scheduled rotation is a week away, so it needs a person.
resource "aws_cloudwatch_metric_alarm" "db_secret_redeploy_failed" {
  alarm_name          = "${local.name_prefix}-db-secret-redeploy-failed"
  alarm_description   = "Redeploying the backend after a database password rotation failed; backend tasks may hold a stale password"
  namespace           = "AWS/States"
  metric_name         = "ExecutionsFailed"
  statistic           = "Sum"
  period              = 300
  evaluation_periods  = 1
  threshold           = 0
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    StateMachineArn = var.db_secret_redeploy_arn
  }

  alarm_actions = local.actions
  ok_actions    = local.actions

  tags = var.tags
}
