name: 'Security Scan'

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
  schedule:
    - cron: '0 0 * * 1' # Weekly on Monday

jobs:
  tfsec:
    name: 'TFSec Security Scan'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run tfsec
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        working_directory: ./terraform
        soft_fail: false
        format: sarif
        out: tfsec-results.sarif

    - name: Upload SARIF results
      uses: github/codeql-action/upload-sarif@v3
      if: success()
      with:
        sarif_file: tfsec-results.sarif

  checkov:
    name: 'Checkov Security Scan'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Checkov
      run: pip install checkov

    - name: Run Checkov
      id: checkov
      run: |
        checkov -d terraform/ \
          --framework terraform \
          --output cli \
          --output sarif \
          --output-file-path . \
          --download-external-modules true || true

    - name: Upload Checkov SARIF results
      uses: github/codeql-action/upload-sarif@v3
      if: ${{ hashFiles('results.sarif') != '' }}
      with:
        sarif_file: results.sarif

  terrascan:
    name: 'Terrascan Security Scan'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Terrascan
      uses: tenable/terrascan-action@v1.5.0
      with:
        iac_type: 'terraform'
        iac_dir: 'terraform/'
        policy_type: 'aws'
        only_warn: false
        sarif_upload: true

    - name: Upload Terrascan SARIF results
      uses: github/codeql-action/upload-sarif@v3
      if: ${{ hashFiles('terrascan.sarif') != '' }}
      with:
        sarif_file: terrascan.sarif

  trivy:
    name: 'Trivy Security Scan'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
        scan-ref: './terraform'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH,MEDIUM'

    - name: Upload Trivy SARIF results
      uses: github/codeql-action/upload-sarif@v3
      if: ${{ hashFiles('trivy-results.sarif') != '' }}
      with:
        sarif_file: trivy-results.sarif

  security-summary:
    name: 'Security Summary'
    runs-on: ubuntu-latest
    needs: [tfsec, checkov, terrascan, trivy]
    if: always()

    steps:
    - name: Security Scan Summary
      run: |
        echo "### Security Scan Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Tool | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|------|--------|" >> $GITHUB_STEP_SUMMARY
        echo "| TFSec | ${{ needs.tfsec.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Checkov | ${{ needs.checkov.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Terrascan | ${{ needs.terrascan.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Trivy | ${{ needs.trivy.result }} |" >> $GITHUB_STEP_SUMMARY