name: 'Terraform Plan'

on:
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-plan.yml'

env:
  TERRAFORM_VERSION: '1.5.7'
  WORKING_DIR: './terraform'
  AWS_REGION: 'ap-southeast-2'

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      if: ${{ secrets.AWS_ACCESS_KEY_ID != '' }}
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      id: init
      run: |
        if [ -n "${{ secrets.TERRAFORM_STATE_BUCKET }}" ]; then
          terraform init \
            -backend-config="bucket=${{ secrets.TERRAFORM_STATE_BUCKET }}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}"
        else
          terraform init -backend=false
        fi
      working-directory: ${{ env.WORKING_DIR }}

    - name: Terraform Plan
      id: plan
      run: |
        if [ -n "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
          terraform plan -no-color -out=tfplan
        else
          echo "Skipping plan - AWS credentials not configured"
          echo "Please add AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to repository secrets"
          exit 0
        fi
      working-directory: ${{ env.WORKING_DIR }}
      continue-on-error: true

    - name: Terraform Show Plan
      id: show
      if: ${{ secrets.AWS_ACCESS_KEY_ID != '' }}
      run: terraform show -no-color tfplan
      working-directory: ${{ env.WORKING_DIR }}

    - name: Comment Plan on PR
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      env:
        PLAN: "terraform\n${{ steps.show.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Plan \`${{ steps.plan.outcome }}\`

          <details><summary>Show Plan</summary>

          \`\`\`hcl
          ${process.env.PLAN}
          \`\`\`

          </details>

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

    - name: Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1