name: 'Terraform Validate'

on:
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-validate.yml'

env:
  TERRAFORM_VERSION: '1.5.7'
  WORKING_DIR: './terraform'

jobs:
  validate:
    name: 'Terraform Validation'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Terraform Format Check
      id: fmt
      run: terraform fmt -check -recursive
      working-directory: ${{ env.WORKING_DIR }}
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init -backend=false
      working-directory: ${{ env.WORKING_DIR }}

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: ${{ env.WORKING_DIR }}

    - name: Validation Summary
      if: always()
      run: |
        echo "### Terraform Validation Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Check | Result |" >> $GITHUB_STEP_SUMMARY
        echo "|-------|--------|" >> $GITHUB_STEP_SUMMARY
        echo "| Format | ${{ steps.fmt.outcome }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Init | ${{ steps.init.outcome }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Validate | ${{ steps.validate.outcome }} |" >> $GITHUB_STEP_SUMMARY