name: 'Terraform Destroy'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        type: choice
        options:
          - dev
          - staging
      confirm:
        description: 'Type "destroy" to confirm'
        required: true

env:
  TERRAFORM_VERSION: '1.5.7'
  WORKING_DIR: './terraform'
  AWS_REGION: 'ap-southeast-2'

jobs:
  confirm-destroy:
    name: 'Confirm Destroy'
    runs-on: ubuntu-latest
    outputs:
      confirmed: ${{ steps.confirm.outputs.confirmed }}

    steps:
    - name: Confirm Destruction
      id: confirm
      run: |
        if [ "${{ github.event.inputs.confirm }}" = "destroy" ]; then
          echo "confirmed=true" >> $GITHUB_OUTPUT
          echo "Destruction confirmed" >> $GITHUB_STEP_SUMMARY
        else
          echo "confirmed=false" >> $GITHUB_OUTPUT
          echo "Destruction NOT confirmed. Type 'destroy' to confirm." >> $GITHUB_STEP_SUMMARY
          exit 1
        fi

  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    needs: confirm-destroy
    if: needs.confirm-destroy.outputs.confirmed == 'true'
    environment: ${{ github.event.inputs.environment }}-destroy

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="bucket=${{ secrets.TERRAFORM_STATE_BUCKET }}" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="region=${{ env.AWS_REGION }}"
      working-directory: ${{ env.WORKING_DIR }}

    - name: Select Workspace
      run: terraform workspace select ${{ github.event.inputs.environment }}
      working-directory: ${{ env.WORKING_DIR }}

    - name: Terraform Plan Destroy
      run: terraform plan -destroy -no-color -out=destroy.tfplan
      working-directory: ${{ env.WORKING_DIR }}

    - name: Terraform Destroy
      run: terraform apply -auto-approve destroy.tfplan
      working-directory: ${{ env.WORKING_DIR }}

    - name: Destruction Summary
      run: |
        echo "### Infrastructure Destroyed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Environment: **${{ github.event.inputs.environment }}**" >> $GITHUB_STEP_SUMMARY
        echo "Destroyed by: **@${{ github.actor }}**" >> $GITHUB_STEP_SUMMARY
        echo "Time: **$(date)**" >> $GITHUB_STEP_SUMMARY